apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    cert-manager-tls: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
     labels:
      app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-auth
                key: username
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-auth
                key: password
          - name: MINIO_DOMAIN
            value: s3.antifausa.net
        volumeMounts:
          - name: config
            mountPath: /root/.minio
          - name: data
            mountPath: /data
        ports:
        - containerPort: 9000
        - containerPort: 9001
        args: ["server", "/data", "--console-address=:9001", "--anonymous", "--json"]
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: minio-config
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: minio-api
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: minio-console
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: minio.antifausa.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-console
            port:
              name: minio-console
  tls:
    - hosts:
      - minio.antifausa.net
      secretName: star-antifausa-net-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: s3.antifausa.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-api
            port:
              name: minio-api
  tls:
    - hosts:
      - s3.antifausa.net
      secretName: star-antifausa-net-cert
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-config
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 8Gi
