apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: k8s@galenguyer.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-api-key-secret
    solvers:
    - dns01:
        cloudflare:
          email: galenguyer@outlook.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
